//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public System.Guid ID { get; set; }
        public string IDParticipant { get; set; }
        public System.Guid IDEvent { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public string Status { get; set; }
        public System.DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Participant Participant { get; set; }
    }
}
